# Generated by Django 2.1 on 2018-08-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'مدیر'), ('employee', 'کارمند'), ('customer', 'مشتری')], max_length=20, null=True),
        ),
    ]
