# Generated by Django 2.1 on 2018-08-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(blank=True, choices=[('payment', 'پرداخت'), ('get', 'برداشت')], max_length=10, null=True, verbose_name='واریز یا برداشت')),
                ('money_type', models.CharField(blank=True, choices=[('dollar', 'دلار'), ('euro', 'یورو'), ('toman', 'تومان')], max_length=10, null=True, verbose_name='نوع پول')),
                ('start', models.IntegerField(blank=True, default=2, null=True, verbose_name='شروع بازه')),
                ('end', models.IntegerField(blank=True, default=200, null=True, verbose_name='انتهای بازه')),
                ('percent', models.FloatField(blank=True, default=2, max_length=5, null=True, verbose_name='درصد کارمزد')),
            ],
        ),
    ]
