# Generated by Django 2.1 on 2018-08-29 06:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('manager', 'مدیر'), ('employee', 'کارمند'), ('customer', 'مشتری')], max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('fixed_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('shaba', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(blank=True, choices=[('payment', 'پرداخت'), ('get', 'برداشت')], max_length=10, null=True, verbose_name='واریز یا برداشت')),
                ('money_type', models.CharField(blank=True, choices=[('dollar', 'دلار'), ('euro', 'یورو'), ('toman', 'تومان')], max_length=10, null=True, verbose_name='نوع پول')),
                ('payment', models.IntegerField(blank=True, default=2, null=True, verbose_name='مبلغ پرداخت')),
                ('job_cost', models.IntegerField(blank=True, default=200, null=True, verbose_name='کارمزد')),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='زمان')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollar', models.IntegerField(blank=True, default=0, null=True)),
                ('euro', models.IntegerField(blank=True, default=0, null=True)),
                ('toman', models.IntegerField(blank=True, default=0, null=True)),
                ('wallet_customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customers_Profile')),
            ],
        ),
    ]
