# Generated by Django 2.1 on 2018-08-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers_profile',
            name='fixed_phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customers_profile',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customers_profile',
            name='shaba',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
