# Generated by Django 2.1 on 2018-08-27 14:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20180826_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(blank=True, choices=[('payment', 'پرداخت'), ('get', 'برداشت')], max_length=10, null=True, verbose_name='واریز یا برداشت')),
                ('money_type', models.CharField(blank=True, choices=[('dollar', 'دلار'), ('euro', 'یورو'), ('toman', 'تومان')], max_length=10, null=True, verbose_name='نوع پول')),
                ('payment', models.IntegerField(blank=True, default=2, null=True, verbose_name='مبلغ پرداخت')),
                ('job_cost', models.IntegerField(blank=True, default=200, null=True, verbose_name='کارمزد')),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='زمان')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollar', models.IntegerField(blank=True, default=0, null=True)),
                ('euro', models.IntegerField(blank=True, default=0, null=True)),
                ('toman', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fieldmodel',
            name='form',
        ),
        migrations.DeleteModel(
            name='kif',
        ),
        migrations.DeleteModel(
            name='WalletMoney',
        ),
        migrations.DeleteModel(
            name='WalletRial',
        ),
        migrations.RemoveField(
            model_name='customers_profile',
            name='fixed_phone',
        ),
        migrations.DeleteModel(
            name='FieldModel',
        ),
        migrations.DeleteModel(
            name='FormModel',
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customers_Profile'),
        ),
    ]
