# Generated by Django 2.1 on 2018-08-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20180829_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers_profile',
            name='fixed_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customers_profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customers_profile',
            name='shaba',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
