# Generated by Django 2.1 on 2018-08-29 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20180829_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers_profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='customers_profile',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
