# Generated by Django 2.1 on 2018-08-29 06:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='زمان')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customers_Profile', verbose_name='مشتری')),
            ],
        ),
        migrations.CreateModel(
            name='Manager_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('manager', 'مدیر'), ('employee', 'کارمند'), ('customer', 'مشتری')], max_length=20, null=True)),
                ('dollarMax', models.IntegerField(blank=True, default=20000, null=True)),
                ('dollarMin', models.IntegerField(blank=True, default=20, null=True)),
                ('euroMax', models.IntegerField(blank=True, default=20000, null=True)),
                ('euroMin', models.IntegerField(blank=True, default=20, null=True)),
                ('tomanMax', models.IntegerField(blank=True, default=400000000, null=True)),
                ('tomanMin', models.IntegerField(blank=True, default=40000, null=True)),
                ('salaryDate', models.IntegerField(blank=True, default=1, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='accesslog',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Manager_Profile', verbose_name='مدیر'),
        ),
    ]
