# Generated by Django 2.1 on 2018-08-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='manager_profile',
            name='dollarMax',
            field=models.IntegerField(blank=True, default=20000, null=True),
        ),
        migrations.AddField(
            model_name='manager_profile',
            name='dollarMin',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AddField(
            model_name='manager_profile',
            name='euroMax',
            field=models.IntegerField(blank=True, default=20000, null=True),
        ),
        migrations.AddField(
            model_name='manager_profile',
            name='euroMin',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AddField(
            model_name='manager_profile',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'مدیر'), ('employee', 'کارمند'), ('customer', 'مشتری')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='manager_profile',
            name='salaryDate',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='manager_profile',
            name='tomanMax',
            field=models.IntegerField(blank=True, default=400000000, null=True),
        ),
        migrations.AddField(
            model_name='manager_profile',
            name='tomanMin',
            field=models.IntegerField(blank=True, default=40000, null=True),
        ),
    ]
